---
title: "Project Checkpoint 1"
author: "Marshall Graham"
date: "November 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(urltools)
library(jsonlite)
library(ggmap)
library(rvest)

```




Read in data on NiceRide, the bike share for the twin cities
```{r, cache=TRUE}

niceRide2016<-read_csv("Nice_ride_data_2016_season\\Nice_ride_data_2016_season\\Nice_ride_trip_history_2016_season.csv")
niceRideLocations<-read_csv("Nice_ride_data_2016_season\\Nice_ride_data_2016_season\\Nice_Ride_2016_Station_Locations.csv")

```

```{r}
nrow(niceRide2016)
```
Read in data on MetroTransit
```{r, cache=TRUE}
metroStops<-read_csv("bus-stops-Oct-2017.csv")
metroRidership<-read_csv("ridership-route-day-Jan2014-Oct2017.csv")
head(metroStops)
head(metroRidership)


```


Visualize where the stops and stations are in the twin cities
```{r, cache=TRUE}
twinCitiesMap<-get_map(location="Minneapolis", zoom= 10)

ggmap(twinCitiesMap)+
   geom_point(data=metroStops, aes(x=site_longitude, y=site_latitude))


#about 100 ft in degrees latitude
ft100<-.0002744

ggmap(twinCitiesMap)+
   geom_point(data=niceRideLocations, aes(x=Longitude, y=Latitude))


```

Limit the bus stops to only stops within a rectangle that encloses the bike stations
```{r}
minBikeLat<-min(niceRideLocations$Latitude)-ft100
maxBikeLat<-max(niceRideLocations$Latitude)+ft100

minBikeLong<-min(niceRideLocations$Longitude)-ft100
maxBikeLong<-max(niceRideLocations$Longitude)+ft100

metroStopsLimited<-metroStops%>%
   filter(site_longitude>minBikeLong&site_longitude<maxBikeLong)%>%
   filter(site_latitude>minBikeLat&site_latitude<maxBikeLat)

ggmap(twinCitiesMap)+
   geom_point(data=metroStopsLimited, aes(x=site_longitude, y=site_latitude))

nrow(metroStopsLimited)



```

Read in data on weather for 2016
```{r}

#source: http://www.dnr.state.mn.us/climate/twin_cities/listings.html
MinneapolisWeather<-read_csv(file="Minneapolis Weather.txt", col_names = c("date", "maxTemp","minTemp","precip","snow","snowDepth"))

MinneapolisWeather<-MinneapolisWeather%>%
   mutate(precip=as.double(replace(precip,precip=="T",0)))%>%
   mutate(snow=as.double(replace(snow,snow=="T",0)))%>%
   mutate(snowDepth=as.double(replace(snowDepth,snowDepth=="T",0)))

```

```{r}

head(metroRidership)
class(metroRidership$dtDate)
class(MinneapolisWeather$date)

metroRidership<-metroRidership%>%
   mutate(dtDate=as.Date(dtDate))
WeatherRiders<-metroRidership%>%
   left_join(MinneapolisWeather, by=c("dtDate"="date"))

AvgDayTemp<-MinneapolisWeather%>%
   mutate(day=yday(date))%>%
   group_by(day)%>%
   summarize(dayTemp=sum((maxTemp+minTemp)/2)/n())

head(AvgDayTemp)
nrow(AvgDayTemp)
WeatherRiders<-WeatherRiders%>%
   mutate(day=yday(dtDate))%>%
   left_join(AvgDayTemp, by="day")%>%
   mutate(tempDiff=(maxTemp+minTemp)/2-dayTemp)%>%
   filter(Schedule!="Holiday")

WeatherRiders1<-WeatherRiders%>%
   filter()%>% 
   mutate(day=as.factor(day), Route=as.factor(Route))

head(WeatherRiders1)

ggplot(WeatherRiders1, aes(x=tempDiff, y=Total_Riders))+
   geom_smooth()
```


Doing same weather analysis with ridership
First get ridership of bikes by day

```{r}
head(niceRide2016)


niceRideDay<-niceRide2016%>%
   mutate(startDate=niceRide2016$`Start date`)%>%
   select("startDate")%>%
   mutate(startDate=as.Date(startDate, "%m/%d/%Y"))%>%
   group_by(startDate)%>%
   summarize(numRiders=n())


head(niceRideDay)

niceRideDay<-niceRideDay%>%
   left_join(MinneapolisWeather, by=c("startDate"="date"))%>%
   mutate(day=yday(startDate))%>%
   left_join(AvgDayTemp,by="day")%>% 
   mutate(tempDiff=(maxTemp+minTemp)/2-dayTemp)

head(niceRideDay)
ggplot(niceRideDay, aes(x=tempDiff, y=numRiders))+
   geom_smooth()

```
